# Generated by Django 3.2.16 on 2023-01-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time2Playapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Item_Order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductStatus',
            field=models.CharField(default='True', max_length=100),
        ),
    ]
