# Generated by Django 4.1.5 on 2023-01-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time2Playapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserType',
            field=models.CharField(default='Cliente', max_length=100),
        ),
    ]
