# Generated by Django 4.1.3 on 2023-01-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time2Playapp', '0002_alter_sales_producttypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='ProductTypeId',
            field=models.IntegerField(),
        ),
    ]
