# Generated by Django 4.1.5 on 2023-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time2Playapp', '0003_alter_sales_producttypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserStatus',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
